/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasemanager_sqlanywhere_andreaquin;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//Librerias de conexion
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Andrea Quin
 */
public class MainFrame extends javax.swing.JFrame {

    Connection connection;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private ConnectionManager connectionManager = new ConnectionManager();

    /**
     * Creates new form MainFrame
     */
    public MainFrame(ConnectionManager connectionManager) {
        initComponents();

        jComboBox1.removeAllItems();
        for (String key : connectionManager.getConnectionKeys()) {
            jComboBox1.addItem(key);
        }

        connectBTN.addActionListener(e -> {
            String key = (String) jComboBox1.getSelectedItem();
            if (key != null) {
                try {
                    connectionManager.setActiveConnection(key);
                    JOptionPane.showMessageDialog(this, "Connected to " + key);
                    new ManagerFrame(connectionManager).setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Connection failed: " + ex.getMessage());
                }
            }
        });

        //ICON
        ImageIcon icon = new ImageIcon(MainFrame.class.getResource("/resources/Icon.png"));
        this.setIconImage(icon.getImage()); 
            }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PortTextbox = new javax.swing.JTextField();
        DatabaseNameTextbox = new javax.swing.JTextField();
        PasswordTextbox = new javax.swing.JPasswordField();
        UsernameTextbox = new javax.swing.JTextField();
        ConnectButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        connectBTN = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        PortTextbox.setBackground(new java.awt.Color(235, 240, 254));
        PortTextbox.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        PortTextbox.setForeground(new java.awt.Color(51, 51, 51));
        PortTextbox.setBorder(null);
        PortTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortTextboxActionPerformed(evt);
            }
        });
        jLayeredPane1.add(PortTextbox);
        PortTextbox.setBounds(240, 420, 310, 40);

        DatabaseNameTextbox.setBackground(new java.awt.Color(235, 240, 254));
        DatabaseNameTextbox.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        DatabaseNameTextbox.setForeground(new java.awt.Color(51, 51, 51));
        DatabaseNameTextbox.setBorder(null);
        DatabaseNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatabaseNameTextboxActionPerformed(evt);
            }
        });
        jLayeredPane1.add(DatabaseNameTextbox);
        DatabaseNameTextbox.setBounds(240, 350, 310, 40);

        PasswordTextbox.setBackground(new java.awt.Color(235, 240, 254));
        PasswordTextbox.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        PasswordTextbox.setForeground(new java.awt.Color(51, 51, 51));
        PasswordTextbox.setBorder(null);
        jLayeredPane1.add(PasswordTextbox);
        PasswordTextbox.setBounds(240, 280, 310, 40);

        UsernameTextbox.setBackground(new java.awt.Color(235, 240, 254));
        UsernameTextbox.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        UsernameTextbox.setForeground(new java.awt.Color(51, 51, 51));
        UsernameTextbox.setBorder(null);
        UsernameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextboxActionPerformed(evt);
            }
        });
        jLayeredPane1.add(UsernameTextbox);
        UsernameTextbox.setBounds(240, 210, 310, 40);

        ConnectButton.setBorderPainted(false);
        ConnectButton.setContentAreaFilled(false);
        ConnectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectButtonMouseClicked(evt);
            }
        });
        jLayeredPane1.add(ConnectButton);
        ConnectButton.setBounds(140, 570, 300, 70);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(750, 20, 310, 40);

        connectBTN.setBackground(new java.awt.Color(153, 204, 255));
        connectBTN.setForeground(new java.awt.Color(0, 0, 0));
        connectBTN.setText("CONNECT");
        jLayeredPane1.add(connectBTN);
        connectBTN.setBounds(850, 70, 110, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Main Page.png"))); // NOI18N
        jLayeredPane1.add(Background);
        Background.setBounds(0, 0, 1200, 675);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextboxActionPerformed

    private void DatabaseNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatabaseNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatabaseNameTextboxActionPerformed

    private void PortTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortTextboxActionPerformed

    private void ConnectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectButtonMouseClicked

        if (UsernameTextbox.getText().isBlank()
                || new String(PasswordTextbox.getPassword()).isBlank()
                || DatabaseNameTextbox.getText().isBlank()
                || PortTextbox.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "⭐ Please, fill in all the information. ⭐", " ERROR! ", JOptionPane.ERROR_MESSAGE);

        } else {

            String username = UsernameTextbox.getText();
            String password = new String(PasswordTextbox.getPassword());
            String databaseName = DatabaseNameTextbox.getText();
            String port = PortTextbox.getText();

            String url = "jdbc:sqlanywhere:UID=" + username
                    + ";PWD=" + password
                    + ";ENG=" + databaseName
                    + ";LINKS=tcpip{port=" + port + "}";

            try {
                Connection conn = DriverManager.getConnection(url);
                JOptionPane.showMessageDialog(this, "✅ Connected successfully!");
                this.connection = conn;

                String alias = JOptionPane.showInputDialog(this, "Enter connection alias:");
                if (alias == null || alias.isBlank()) {
                    alias = username + "@" + databaseName;
                }

                ConnectionManager.ConnectionInfo info = new ConnectionManager.ConnectionInfo(
                        Integer.parseInt(port),
                        databaseName,
                        username,
                        password
                );
                connectionManager.addConnection(alias, info);

                ManagerFrame frame = new ManagerFrame(connectionManager);
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);

                this.setVisible(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "❌ Connection failed: " + ex.getMessage());
                ex.printStackTrace();
            }

        }


    }//GEN-LAST:event_ConnectButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ConnectButton;
    private javax.swing.JTextField DatabaseNameTextbox;
    private javax.swing.JPasswordField PasswordTextbox;
    private javax.swing.JTextField PortTextbox;
    private javax.swing.JTextField UsernameTextbox;
    private javax.swing.JButton connectBTN;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

}
